import { randomUUID } from 'node:crypto';
import type { Knex } from 'knex';
import type { Db } from './knex.js';
import { notFound } from '../lib/errors.js';

/** Ids are generated by the application, as they were under Prisma's `@default(uuid())`. */
export const newId = (): string => randomUUID();

/**
 * Insert a row and return it.
 *
 * MySQL has no `RETURNING`, so the previous one-statement `create()` becomes an
 * insert followed by a read. Generating the id up front makes that read exact
 * rather than a guess from `insertId`, which is meaningless for a CHAR(36) key.
 */
export async function insertReturning<T extends Knex.TableNames>(
  db: Db,
  table: T,
  data: Partial<Knex.TableType<T>> & { id?: string },
): Promise<Knex.TableType<T>> {
  const id = data.id ?? newId();
  await db(table).insert({ ...data, id } as never);
  const row = await db(table)
    .where({ id } as never)
    .first();
  if (!row) throw new Error(`Insert into ${String(table)} did not produce a readable row`);
  return row as Knex.TableType<T>;
}

/**
 * Update a row and return the new state. Same reason as above: no RETURNING.
 * Returns null when the id does not exist, so callers can distinguish "no such
 * row" from "nothing changed".
 */
export async function updateReturning<T extends Knex.TableNames>(
  db: Db,
  table: T,
  id: string,
  data: Partial<Knex.TableType<T>>,
): Promise<Knex.TableType<T> | null> {
  await db(table)
    .where({ id } as never)
    .update(data as never);
  const row = await db(table)
    .where({ id } as never)
    .first();
  return (row as Knex.TableType<T>) ?? null;
}

/** Mirrors Prisma's `findUniqueOrThrow`, including the 404 the API relied on. */
export async function firstOrThrow<T>(query: Promise<T | undefined>, what = 'Record'): Promise<T> {
  const row = await query;
  if (!row) throw notFound(what);
  return row;
}

/** Single COUNT(*) as a number; MySQL returns it as a string under bigNumberStrings. */
export async function countRows(query: Knex.QueryBuilder): Promise<number> {
  const result = (await query.clone().clearSelect().clearOrder().count({ n: '*' }).first()) as
    | { n: number | string }
    | undefined;
  return Number(result?.n ?? 0);
}

/**
 * Runs the page query and its count together.
 *
 * Cloning before paginating matters: applying limit/offset to the same builder
 * used for the count would return "how many are on this page", not "how many
 * exist" — a bug that only shows up once there is a second page.
 */
export async function paginateQuery<Row>(
  query: Knex.QueryBuilder,
  page: number,
  pageSize: number,
): Promise<{ items: Row[]; total: number }> {
  const [items, total] = await Promise.all([
    query.clone().limit(pageSize).offset((page - 1) * pageSize) as unknown as Promise<Row[]>,
    countRows(query),
  ]);
  return { items, total };
}

/**
 * Loads related rows for a set of parents in one query and groups them by key.
 *
 * This replaces Prisma's `include`. Doing it as one `WHERE IN` per relation
 * rather than a query per parent is what keeps list endpoints off the N+1 path
 * they would otherwise fall into.
 */
export function groupBy<Row, K extends keyof Row>(rows: Row[], key: K): Map<Row[K], Row[]> {
  const map = new Map<Row[K], Row[]>();
  for (const row of rows) {
    const k = row[key];
    const existing = map.get(k);
    if (existing) existing.push(row);
    else map.set(k, [row]);
  }
  return map;
}

/** Same, for a one-to-one relation. */
export function indexBy<Row, K extends keyof Row>(rows: Row[], key: K): Map<Row[K], Row> {
  return new Map(rows.map((row) => [row[key], row]));
}

/** Deduplicated, non-null foreign keys — the input to a relation load. */
export function idsOf<Row>(rows: Row[], ...keys: (keyof Row)[]): string[] {
  const set = new Set<string>();
  for (const row of rows) {
    for (const key of keys) {
      const value = row[key];
      if (typeof value === 'string' && value) set.add(value);
    }
  }
  return [...set];
}

/** The public shape of a person wherever the API embeds one. */
export const PERSON_COLUMNS = ['id', 'name', 'email', 'role', 'jobTitle', 'avatarColor'] as const;
export interface PersonRef {
  id: string;
  name: string;
  email?: string;
  role?: string;
  jobTitle?: string | null;
  avatarColor: string | null;
}
